x-environment:
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_2025_postgis'
    container_name: prge_bgm_postgis-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-remote-data-${ENV_NAME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  geoserver:
    build:
      context: ..
      dockerfile: docker/geoserver/Dockerfile
    image: 'prge_2025_geoserver'
    container_name: prge_bgm_geoserver-${ENV_NAME}
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - ../.tmp/data-${ENV_NAME}:/opt/geoserver_data
      - ../.tmp/geoserver-config-${ENV_NAME}:/opt/geoserver/data_dir
    depends_on:
      postgis:
        condition: service_healthy

  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    image: 'prge_2025_fastapi'
    container_name: prge_nb_fastapi-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
      - ENV_NAME=${ENV_NAME}
    ports:
      - ${FASTAPI_PORT}:10000
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  postgis-remote-data-${ENV_NAME}: