name: push and deploy

on:
  push:
    branches:
      - env-test
      - env-qa
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on:
      - self-hosted
    environment: ${{github.ref_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print
        run: echo 'witaj'

      - name: Stop existing containers
        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-remote.yml -p remote-prge-${{github.ref_name}} down || true

      - name: uruchom Å›rodowisko docker-compose
        env:
          ENV_NAME: ${{github.ref_name}}
          #DB
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          GEOSERVER_PORT: ${{secrets.GEOSERVER_PORT}}
          FASTAPI_PORT: ${{secrets.FASTAPI_PORT}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-remote.yml -p remote-prge-${{github.ref_name}} up --build -d